-- Operazione di generaione del SQL per oracle
-- Data i creazione dello script:Thu Jul 09 19:21:42 CEST 2015
-- Specifica:GeoSmartCity Building Data Model
-- Specifica identificatore:
-- Specifica numero di versione:2.1
-- Specifica data di creazione:05 maggio 2015  - 15:02:14
-- Specifica data di ultima modifica:09 luglio 2015  - 19:16:48
-- Specifica stato:work in progress ( 01 agosto 2014  - 19:25:00 )
-- Dps nome:Gsc_oracle
-- Dps data di creazione:14 maggio 2015  - 10:17:13
-- Dps Spatial Reference System:EPSG:3044
-- Dps nome del modello implementativo:SQL_ESF_FLAT
-- Dps versione del modello implementativo:1.0
-- Dps database del modello implementativo:Oracle
-- Dps implementazione sottoaree B3D:2D
-- Dps implementazione eventi - stratti - sottoaree:non connessi
-- Saranno create:
-- 	4 tabelle per le classi
-- 	21 tabelle per la trascodifica dei domini
-- 	0 tabelle segment event subregion
-- 	9 tabelle per i datatype
-- 	5 tabelle di supporto ad attributi multivalore
-- 	0 tabelle per gli strati topologici
-- 	0 tabelle per ruoli e associzioni
-- 	0 tabelle per codifica dei valori nulli


-- 
-- Generazione tabelle per la trascodifica dei domini
-- 


-- 
-- CREATE TABLE: D_OCCUPANCYTYPE
-- Rappresenta la tabella di trascodifica del dominio: Occupancy type value - OCCUPANCYTYPE
-- 

CREATE TABLE D_OCCUPANCYTYPE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_BUILDINGNATURE
-- Rappresenta la tabella di trascodifica del dominio: Building nature value - BUILDINGNATURE
-- 

CREATE TABLE D_BUILDINGNATURE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: H_OWNERSHIPTYPE
-- Rappresenta la tabella di trascodifica del dominio gerarchico: Ownership type value - OWNERSHIPTYPE
-- 

CREATE TABLE H_OWNERSHIPTYPE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(850),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_BUILDINGTYPE
-- Rappresenta la tabella di trascodifica del dominio: Building type - BUILDINGTYPE
-- 

CREATE TABLE D_BUILDINGTYPE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: H_LOCATION
-- Rappresenta la tabella di trascodifica del dominio gerarchico: Location - LOCATION
-- 

CREATE TABLE H_LOCATION (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(850),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_ENERGYTYPE
-- Rappresenta la tabella di trascodifica del dominio: Energy type value - ENERGYTYPE
-- 

CREATE TABLE D_ENERGYTYPE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_INSTALLATIONNATURE
-- Rappresenta la tabella di trascodifica del dominio: Installation nature value - INSTALLATIONNATURE
-- 

CREATE TABLE D_INSTALLATIONNATURE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: H_ENERGYSOURCE
-- Rappresenta la tabella di trascodifica del dominio gerarchico: Energy source value - ENERGYSOURCE
-- 

CREATE TABLE H_ENERGYSOURCE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(850),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_PERF_CLASS
-- Rappresenta la tabella di trascodifica del dominio: Energy performance class - PERF_CLASS
-- 

CREATE TABLE D_PERF_CLASS (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_CLGE
-- Rappresenta la tabella di trascodifica del dominio: Clge official area reference value - CLGE
-- 

CREATE TABLE D_CLGE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_TYPE_VALUE
-- Rappresenta la tabella di trascodifica del dominio: Type value - TYPE_VALUE
-- 

CREATE TABLE D_TYPE_VALUE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_HEIGHTSTATUS
-- Rappresenta la tabella di trascodifica del dominio: Height status value - HEIGHTSTATUS
-- 

CREATE TABLE D_HEIGHTSTATUS (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: H_CURRENTUSE
-- Rappresenta la tabella di trascodifica del dominio gerarchico: Current use value - CURRENTUSE
-- 

CREATE TABLE H_CURRENTUSE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(850),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_CONDITIONOFCONSTRUCTION
-- Rappresenta la tabella di trascodifica del dominio: Condition of construction value - CONDITIONOFCONSTRUCTION
-- 

CREATE TABLE D_CONDITIONOFCONSTRUCTION (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_ENERGYUSE
-- Rappresenta la tabella di trascodifica del dominio: Energy use value - ENERGYUSE
-- 

CREATE TABLE D_ENERGYUSE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_REFURBISHMENTLEVEL
-- Rappresenta la tabella di trascodifica del dominio: Refurbishment level - REFURBISHMENTLEVEL
-- 

CREATE TABLE D_REFURBISHMENTLEVEL (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_ROOFTYPE
-- Rappresenta la tabella di trascodifica del dominio: Roof type value - ROOFTYPE
-- 

CREATE TABLE D_ROOFTYPE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_ELEVATIONREFERENCE
-- Rappresenta la tabella di trascodifica del dominio: Elevation reference - ELEVATIONREFERENCE
-- 

CREATE TABLE D_ELEVATIONREFERENCE (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_MATERIAL
-- Rappresenta la tabella di trascodifica del dominio: Material value - MATERIAL
-- 

CREATE TABLE D_MATERIAL (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: D_HEATINGSYSTEM
-- Rappresenta la tabella di trascodifica del dominio: Heating system value - HEATINGSYSTEM
-- 

CREATE TABLE D_HEATINGSYSTEM (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(160),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: H_UOM
-- Rappresenta la tabella di trascodifica del dominio gerarchico: Unit of measure - UOM
-- 

CREATE TABLE H_UOM (
	CODE  VARCHAR2(80) NOT NULL,
	NAME  VARCHAR2(850),
	DEFINITION  VARCHAR2(1200),
	ALPHACODE  VARCHAR2(80)
);

-- 
-- Generazione tabelle per le classi
-- 


-- 
-- CREATE TABLE: BUILDINGS
-- Rappresenta la classe: Buildings - BUILDINGS
-- 

CREATE TABLE BUILDINGS (
	UUID  VARCHAR2(70) NOT NULL,
	BUILDINGTYPE  VARCHAR2(80),
	CONDITION  VARCHAR2(80) NOT NULL,
	CONNECTION_ELECTRICITY  CHAR(1) ,
	CONNECTION_GAS  CHAR(1) ,
	CONNECTION_SEWAGE  CHAR(1) ,
	CONNECTION_THERMAL  CHAR(1) ,
	CONNECTION_WATER  CHAR(1) ,
	DATE_C_BEGINNING  NUMBER(15,0) ,
	DATE_C_END  NUMBER(15,0) ,
	DATE_R_BEGINNING  NUMBER(15,0) ,
	DATE_R_END  NUMBER(15,0) ,
	DIST_FLOOR  VARCHAR2(40) NOT NULL,
	ELEV_REF  VARCHAR2(80),
	FLOORS  NUMBER(15,0) ,
	HEIGHT_HEIGHT_LOW  VARCHAR2(80),
	HEIGHT_HEIGHT_REF  VARCHAR2(80) NOT NULL,
	HEIGHT_HEIGHT_STAT  VARCHAR2(80) NOT NULL,
	HEIGHT_HEIGHT_VAL  DOUBLE PRECISION,
	H_FLOOR  DOUBLE PRECISION,
	IDENTIFIER_ID_LOC  VARCHAR2(40),
	IDENTIFIER_ID_NAME  VARCHAR2(40),
	IDENTIFIER_ID_VERS  VARCHAR2(40),
	INST_METER  CHAR(1) ,
	INST_PHOTOV  CHAR(1) ,
	INST_SOLAR  CHAR(1) ,
	INST_THRPLANT  CHAR(1) ,
	LIFESPAN_BEGINNING  NUMBER(15,0) ,
	LIFESPAN_END  NUMBER(15,0) ,
	NAME  VARCHAR2(100),
	NATURE  VARCHAR2(80),
	OCCUPANTS  NUMBER(15,0) ,
	OWNERSHIP  VARCHAR2(80),
	REFURBISH  VARCHAR2(80),
	ROOF_TYPE  VARCHAR2(80),
	UNITS  NUMBER(15,0) ,
	USE_S  VARCHAR2(80) NOT NULL,
	VERT_SURF  DOUBLE PRECISION,
	VOLUME_SOURCE  VARCHAR2(40),
	VOLUME_VALUE  DOUBLE PRECISION,
	GEOMETRY2D MDSYS.SDO_Geometry NOT NULL
);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES (
	'BUILDINGS', 
	'GEOMETRY2D', 
	MDSYS.SDO_DIM_ARRAY( 
		MDSYS.SDO_DIM_ELEMENT('X', 231991.5007 , 768008.4993 , 0.01),
		MDSYS.SDO_DIM_ELEMENT('Y', 4065788.6515 , 7768690.1087 , 0.01)
	), 3044
); 


-- 
-- CREATE TABLE: THERMALZONE
-- Rappresenta la classe: Thermal zone (building part) - THERMALZONE
-- 

CREATE TABLE THERMALZONE (
	UUID  VARCHAR2(70) NOT NULL,
	ENERGYPERFORMANCE_PERF_CLASS  VARCHAR2(80),
	ENERGYPERFORMANCE_PERF_DATE  DATE ,
	ENERGYPERFORMANCE_PERF_METHOD  VARCHAR2(100),
	ENERGYPERFORMANCE_PERF_UOM  VARCHAR2(80),
	ENERGYPERFORMANCE_PERF_VALUE  NUMBER(15,0) ,
	OCCUPANTS_OCC_VALUE  NUMBER(15,0) ,
	OCCUPANTS_OCC_TYPE  VARCHAR2(80),
	VOLUME_SOURCE  VARCHAR2(40),
	VOLUME_VALUE  DOUBLE PRECISION,
	UUID_TZ2BDG  VARCHAR2(70) NOT NULL
);

-- 
-- CREATE TABLE: INSTALLATION
-- Rappresenta la classe: Installation - INSTALLATION
-- 

CREATE TABLE INSTALLATION (
	UUID  VARCHAR2(70) NOT NULL,
	CONDITION  VARCHAR2(80) NOT NULL,
	DATE_ACTIVATION  DATE ,
	DATE_C_BEGINNING  NUMBER(15,0) ,
	DATE_C_END  NUMBER(15,0) ,
	DATE_R_BEGINNING  NUMBER(15,0) ,
	DATE_R_END  NUMBER(15,0) ,
	ELEV_REF  VARCHAR2(80),
	ENERGY_ESTIMATED  DOUBLE PRECISION,
	ENERGY_PRODUCED  DOUBLE PRECISION,
	HEIGHT_HEIGHT_LOW  VARCHAR2(80),
	HEIGHT_HEIGHT_REF  VARCHAR2(80) NOT NULL,
	HEIGHT_HEIGHT_STAT  VARCHAR2(80) NOT NULL,
	HEIGHT_HEIGHT_VAL  DOUBLE PRECISION,
	IDENTIFIER_ID_LOC  VARCHAR2(40),
	IDENTIFIER_ID_NAME  VARCHAR2(40),
	IDENTIFIER_ID_VERS  VARCHAR2(40),
	INSTALLATION_NATURE  VARCHAR2(80) NOT NULL,
	LIFESPAN_BEGINNING  NUMBER(15,0) ,
	LIFESPAN_END  NUMBER(15,0) ,
	NAME  VARCHAR2(100),
	OWNERSHIP  VARCHAR2(80),
	POWER  DOUBLE PRECISION,
	PURPOSE  VARCHAR2(40),
	SURFACE  DOUBLE PRECISION,
	TYPE  VARCHAR2(80),
	GEOMETRY2D MDSYS.SDO_Geometry NOT NULL
);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES (
	'INSTALLATION', 
	'GEOMETRY2D', 
	MDSYS.SDO_DIM_ARRAY( 
		MDSYS.SDO_DIM_ELEMENT('X', 231991.5007 , 768008.4993 , 0.01),
		MDSYS.SDO_DIM_ELEMENT('Y', 4065788.6515 , 7768690.1087 , 0.01)
	), 3044
); 


-- 
-- CREATE TABLE: CONVERSION
-- Rappresenta la classe: Conversion class - CONVERSION
-- 

CREATE TABLE CONVERSION (
	UUID  VARCHAR2(70) NOT NULL,
	INPUT  VARCHAR2(80) NOT NULL,
	LOCATION  VARCHAR2(80),
	OUTPUT  VARCHAR2(80) NOT NULL,
	VALUE  DOUBLE PRECISION NOT NULL,
	YEAR  DATE 
);

-- 
-- Generazione tabelle per i datatype
-- 


-- 
-- CREATE TABLE: BUILDINGS_ELEVATION_T
-- Rappresenta il datatype: Elevation - ELEVATION
-- 

CREATE TABLE BUILDINGS_ELEVATION_T (
	UUID  VARCHAR2(70),
	ELEVATION_ELEV_VAL  NUMBER(15,0) ,
	ELEVATION_ELEVATIONREFERENCE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: THERMALZONE_OFFICIALAREA_T
-- Rappresenta il datatype: Official area - OFF_AREA
-- 

CREATE TABLE THERMALZONE_OFFICIALAREA_T (
	UUID  VARCHAR2(70),
	OFFICIALAREA_AREA_REF  VARCHAR2(80),
	OFFICIALAREA_VALUE  DOUBLE PRECISION
);

-- 
-- CREATE TABLE: BUILDINGS_EXT_REF_T
-- Rappresenta il datatype: External reference - EXT_REF
-- 

CREATE TABLE BUILDINGS_EXT_REF_T (
	UUID  VARCHAR2(70),
	EXT_REF_IDENTIFIER  VARCHAR2(100),
	EXT_REF_INF_SYS_NAME  VARCHAR2(100),
	EXT_REF_REFERENCE  VARCHAR2(40)
);

-- 
-- CREATE TABLE: THERMALZONE_ENERGYAMOUNT_T
-- Rappresenta il datatype: Energy amount - EnergyAmount
-- 

CREATE TABLE THERMALZONE_ENERGYAMOUNT_T (
	UUID  VARCHAR2(70),
	ENERGYAMOUNT_E_AMOUNT  DOUBLE PRECISION,
	ENERGYAMOUNT_E_SOURCE  VARCHAR2(80),
	ENERGYAMOUNT_E_TYPE  VARCHAR2(80),
	ENERGYAMOUNT_E_USE  VARCHAR2(80),
	ENERGYAMOUNT_E_YEAR  DATE ,
	ENERGYAMOUNT_E_UOM  VARCHAR2(80),
	ENERGYAMOUNT_ESTIMATEDCO2  DOUBLE PRECISION
);

-- 
-- CREATE TABLE: INSTALLATION_ELEVATION_T
-- Rappresenta il datatype: Elevation - ELEVATION
-- 

CREATE TABLE INSTALLATION_ELEVATION_T (
	UUID  VARCHAR2(70),
	ELEVATION_ELEV_VAL  NUMBER(15,0) ,
	ELEVATION_ELEVATIONREFERENCE  VARCHAR2(80)
);

-- 
-- CREATE TABLE: BUILDINGS_ENERGYAMOUNT_T
-- Rappresenta il datatype: Energy amount - EnergyAmount
-- 

CREATE TABLE BUILDINGS_ENERGYAMOUNT_T (
	UUID  VARCHAR2(70),
	ENERGYAMOUNT_E_AMOUNT  DOUBLE PRECISION,
	ENERGYAMOUNT_E_SOURCE  VARCHAR2(80),
	ENERGYAMOUNT_E_TYPE  VARCHAR2(80),
	ENERGYAMOUNT_E_USE  VARCHAR2(80),
	ENERGYAMOUNT_E_YEAR  DATE ,
	ENERGYAMOUNT_E_UOM  VARCHAR2(80),
	ENERGYAMOUNT_ESTIMATEDCO2  DOUBLE PRECISION
);

-- 
-- CREATE TABLE: BUILDINGS_USE_M_T
-- Rappresenta il datatype: Current use - CURR_USE
-- 

CREATE TABLE BUILDINGS_USE_M_T (
	UUID  VARCHAR2(70),
	USE_M_CURRENTUSE  VARCHAR2(80),
	USE_M_PERCENTAGE  NUMBER(15,0) 
);

-- 
-- CREATE TABLE: BUILDINGS_RENEWABLE_POTENTIA_T
-- Rappresenta il datatype: Renewable energy potential - RENEWABLEPOTENTIAL
-- 

CREATE TABLE BUILDINGS_RENEWABLE_POTENTIA_T (
	UUID  VARCHAR2(70),
	RENEWABLE_POTEN_RENEWABLE_SOUR  VARCHAR2(80),
	RENEWABLE_POTENTIAL_VALUE  DOUBLE PRECISION
);

-- 
-- CREATE TABLE: INSTALLATION_EXT_REF_T
-- Rappresenta il datatype: External reference - EXT_REF
-- 

CREATE TABLE INSTALLATION_EXT_REF_T (
	UUID  VARCHAR2(70),
	EXT_REF_IDENTIFIER  VARCHAR2(100),
	EXT_REF_INF_SYS_NAME  VARCHAR2(100),
	EXT_REF_REFERENCE  VARCHAR2(40)
);

-- 
-- Generazione tabelle di supporto ad attributi multivalore
-- 


-- 
-- CREATE TABLE: BUILDINGS_FACADE_MAT
-- Rappresenta la tabella di appoggio per l'attributo multivalore: material of facade - FACADE_MAT
-- 

CREATE TABLE BUILDINGS_FACADE_MAT (
	UUID  VARCHAR2(70) NOT NULL,
	FACADE_MAT  VARCHAR2(80) NOT NULL
);

-- 
-- CREATE TABLE: THERMALZONE_HEATINGSOURCE
-- Rappresenta la tabella di appoggio per l'attributo multivalore: heatingsource - heatingSource
-- 

CREATE TABLE THERMALZONE_HEATINGSOURCE (
	UUID  VARCHAR2(70) NOT NULL,
	HEATINGSOURCE  VARCHAR2(80) NOT NULL
);

-- 
-- CREATE TABLE: THERMALZONE_HEATINGSYSTEM
-- Rappresenta la tabella di appoggio per l'attributo multivalore: heatingsystem - heatingSystem
-- 

CREATE TABLE THERMALZONE_HEATINGSYSTEM (
	UUID  VARCHAR2(70) NOT NULL,
	HEATINGSYSTEM  VARCHAR2(80) NOT NULL
);

-- 
-- CREATE TABLE: BUILDINGS_ROOF_MAT
-- Rappresenta la tabella di appoggio per l'attributo multivalore: material of roof - ROOF_MAT
-- 

CREATE TABLE BUILDINGS_ROOF_MAT (
	UUID  VARCHAR2(70) NOT NULL,
	ROOF_MAT  VARCHAR2(80) NOT NULL
);

-- 
-- CREATE TABLE: BUILDINGS_STRUCTURE_MAT
-- Rappresenta la tabella di appoggio per l'attributo multivalore: material of structure - STRUCTURE_MAT
-- 

CREATE TABLE BUILDINGS_STRUCTURE_MAT (
	UUID  VARCHAR2(70) NOT NULL,
	STRUCTURE_MAT  VARCHAR2(80) NOT NULL
);

-- 
-- Generazione tabelle per la trascodifica dei domini
-- 


-- 
-- DOMAIN CONSTRAINT: D_OCCUPANCYTYPE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Occupancy type value - OCCUPANCYTYPE
-- 

ALTER TABLE D_OCCUPANCYTYPE ADD CONSTRAINT D_OCCUPANCYTYPE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_BUILDINGNATURE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Building nature value - BUILDINGNATURE
-- 

ALTER TABLE D_BUILDINGNATURE ADD CONSTRAINT D_BUILDINGNATURE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: H_OWNERSHIPTYPE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Ownership type value - OWNERSHIPTYPE
-- 

ALTER TABLE H_OWNERSHIPTYPE ADD CONSTRAINT H_OWNERSHIPTYPE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_BUILDINGTYPE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Building type - BUILDINGTYPE
-- 

ALTER TABLE D_BUILDINGTYPE ADD CONSTRAINT D_BUILDINGTYPE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: H_LOCATION
-- PRIMARY KEY per la tabella di trascodifica del dominio : Location - LOCATION
-- 

ALTER TABLE H_LOCATION ADD CONSTRAINT H_LOCATION_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_ENERGYTYPE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Energy type value - ENERGYTYPE
-- 

ALTER TABLE D_ENERGYTYPE ADD CONSTRAINT D_ENERGYTYPE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_INSTALLATIONNATURE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Installation nature value - INSTALLATIONNATURE
-- 

ALTER TABLE D_INSTALLATIONNATURE ADD CONSTRAINT D_INSTALLATIONNATURE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: H_ENERGYSOURCE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Energy source value - ENERGYSOURCE
-- 

ALTER TABLE H_ENERGYSOURCE ADD CONSTRAINT H_ENERGYSOURCE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_PERF_CLASS
-- PRIMARY KEY per la tabella di trascodifica del dominio : Energy performance class - PERF_CLASS
-- 

ALTER TABLE D_PERF_CLASS ADD CONSTRAINT D_PERF_CLASS_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_CLGE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Clge official area reference value - CLGE
-- 

ALTER TABLE D_CLGE ADD CONSTRAINT D_CLGE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_TYPE_VALUE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Type value - TYPE_VALUE
-- 

ALTER TABLE D_TYPE_VALUE ADD CONSTRAINT D_TYPE_VALUE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_HEIGHTSTATUS
-- PRIMARY KEY per la tabella di trascodifica del dominio : Height status value - HEIGHTSTATUS
-- 

ALTER TABLE D_HEIGHTSTATUS ADD CONSTRAINT D_HEIGHTSTATUS_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: H_CURRENTUSE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Current use value - CURRENTUSE
-- 

ALTER TABLE H_CURRENTUSE ADD CONSTRAINT H_CURRENTUSE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_CONDITIONOFCONSTRUCTION
-- PRIMARY KEY per la tabella di trascodifica del dominio : Condition of construction value - CONDITIONOFCONSTRUCTION
-- 

ALTER TABLE D_CONDITIONOFCONSTRUCTION ADD CONSTRAINT D_CONDITIONOFCONSTRUCTION_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_ENERGYUSE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Energy use value - ENERGYUSE
-- 

ALTER TABLE D_ENERGYUSE ADD CONSTRAINT D_ENERGYUSE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_REFURBISHMENTLEVEL
-- PRIMARY KEY per la tabella di trascodifica del dominio : Refurbishment level - REFURBISHMENTLEVEL
-- 

ALTER TABLE D_REFURBISHMENTLEVEL ADD CONSTRAINT D_REFURBISHMENTLEVEL_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_ROOFTYPE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Roof type value - ROOFTYPE
-- 

ALTER TABLE D_ROOFTYPE ADD CONSTRAINT D_ROOFTYPE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_ELEVATIONREFERENCE
-- PRIMARY KEY per la tabella di trascodifica del dominio : Elevation reference - ELEVATIONREFERENCE
-- 

ALTER TABLE D_ELEVATIONREFERENCE ADD CONSTRAINT D_ELEVATIONREFERENCE_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_MATERIAL
-- PRIMARY KEY per la tabella di trascodifica del dominio : Material value - MATERIAL
-- 

ALTER TABLE D_MATERIAL ADD CONSTRAINT D_MATERIAL_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: D_HEATINGSYSTEM
-- PRIMARY KEY per la tabella di trascodifica del dominio : Heating system value - HEATINGSYSTEM
-- 

ALTER TABLE D_HEATINGSYSTEM ADD CONSTRAINT D_HEATINGSYSTEM_PK PRIMARY KEY (CODE);


-- 
-- DOMAIN CONSTRAINT: H_UOM
-- PRIMARY KEY per la tabella di trascodifica del dominio : Unit of measure - UOM
-- 

ALTER TABLE H_UOM ADD CONSTRAINT H_UOM_PK PRIMARY KEY (CODE);


-- 
-- Generazione PK e FK per le classi
-- 


-- 
-- TABLE CONSTRAINT: BUILDINGS
-- PRIMARY KEY per la tabella della classe : Buildings - BUILDINGS
-- 

ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_PK PRIMARY KEY (UUID);


-- 
-- TABLE CONSTRAINT: THERMALZONE
-- PRIMARY KEY per la tabella della classe : Thermal zone (building part) - THERMALZONE
-- 

ALTER TABLE THERMALZONE ADD CONSTRAINT THERMALZONE_PK PRIMARY KEY (UUID);


-- 
-- TABLE CONSTRAINT: INSTALLATION
-- PRIMARY KEY per la tabella della classe : Installation - INSTALLATION
-- 

ALTER TABLE INSTALLATION ADD CONSTRAINT INSTALLATION_PK PRIMARY KEY (UUID);


-- 
-- TABLE CONSTRAINT: CONVERSION
-- PRIMARY KEY per la tabella della classe : Conversion class - CONVERSION
-- 

ALTER TABLE CONVERSION ADD CONSTRAINT CONVERSION_PK PRIMARY KEY (UUID);


-- 
-- TABLE CONSTRAINT: BUILDINGS
-- FOREIGN KEY per la tabella della classe : Buildings - BUILDINGS
-- 

ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK1 FOREIGN KEY (BUILDINGTYPE) REFERENCES  D_BUILDINGTYPE (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK2 FOREIGN KEY (CONDITION) REFERENCES  D_CONDITIONOFCONSTRUCTION (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK3 FOREIGN KEY (ELEV_REF) REFERENCES  D_ELEVATIONREFERENCE (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK4 FOREIGN KEY (HEIGHT_HEIGHT_LOW) REFERENCES  D_ELEVATIONREFERENCE (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK5 FOREIGN KEY (HEIGHT_HEIGHT_REF) REFERENCES  D_ELEVATIONREFERENCE (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK6 FOREIGN KEY (HEIGHT_HEIGHT_STAT) REFERENCES  D_HEIGHTSTATUS (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK7 FOREIGN KEY (NATURE) REFERENCES  D_BUILDINGNATURE (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK8 FOREIGN KEY (OWNERSHIP) REFERENCES  H_OWNERSHIPTYPE (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK9 FOREIGN KEY (REFURBISH) REFERENCES  D_REFURBISHMENTLEVEL (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK10 FOREIGN KEY (ROOF_TYPE) REFERENCES  D_ROOFTYPE (CODE) ;
ALTER TABLE BUILDINGS ADD CONSTRAINT BUILDINGS_FK11 FOREIGN KEY (USE_S) REFERENCES  H_CURRENTUSE (CODE) ;


-- 
-- TABLE CONSTRAINT: THERMALZONE
-- FOREIGN KEY per la tabella della classe : Thermal zone (building part) - THERMALZONE
-- 

ALTER TABLE THERMALZONE ADD CONSTRAINT THERMALZONE_FK1 FOREIGN KEY (ENERGYPERFORMANCE_PERF_CLASS) REFERENCES  D_PERF_CLASS (CODE) ;
ALTER TABLE THERMALZONE ADD CONSTRAINT THERMALZONE_FK2 FOREIGN KEY (ENERGYPERFORMANCE_PERF_UOM) REFERENCES  H_UOM (CODE) ;
ALTER TABLE THERMALZONE ADD CONSTRAINT THERMALZONE_FK3 FOREIGN KEY (OCCUPANTS_OCC_TYPE) REFERENCES  D_OCCUPANCYTYPE (CODE) ;
ALTER TABLE THERMALZONE ADD CONSTRAINT THERMALZONE_FK4 FOREIGN KEY (UUID_TZ2BDG) REFERENCES  BUILDINGS (UUID) ;


-- 
-- TABLE CONSTRAINT: INSTALLATION
-- FOREIGN KEY per la tabella della classe : Installation - INSTALLATION
-- 

ALTER TABLE INSTALLATION ADD CONSTRAINT INSTALLATION_FK1 FOREIGN KEY (CONDITION) REFERENCES  D_CONDITIONOFCONSTRUCTION (CODE) ;
ALTER TABLE INSTALLATION ADD CONSTRAINT INSTALLATION_FK2 FOREIGN KEY (ELEV_REF) REFERENCES  D_ELEVATIONREFERENCE (CODE) ;
ALTER TABLE INSTALLATION ADD CONSTRAINT INSTALLATION_FK3 FOREIGN KEY (HEIGHT_HEIGHT_LOW) REFERENCES  D_ELEVATIONREFERENCE (CODE) ;
ALTER TABLE INSTALLATION ADD CONSTRAINT INSTALLATION_FK4 FOREIGN KEY (HEIGHT_HEIGHT_REF) REFERENCES  D_ELEVATIONREFERENCE (CODE) ;
ALTER TABLE INSTALLATION ADD CONSTRAINT INSTALLATION_FK5 FOREIGN KEY (HEIGHT_HEIGHT_STAT) REFERENCES  D_HEIGHTSTATUS (CODE) ;
ALTER TABLE INSTALLATION ADD CONSTRAINT INSTALLATION_FK6 FOREIGN KEY (INSTALLATION_NATURE) REFERENCES  D_INSTALLATIONNATURE (CODE) ;
ALTER TABLE INSTALLATION ADD CONSTRAINT INSTALLATION_FK7 FOREIGN KEY (OWNERSHIP) REFERENCES  H_OWNERSHIPTYPE (CODE) ;
ALTER TABLE INSTALLATION ADD CONSTRAINT INSTALLATION_FK8 FOREIGN KEY (TYPE) REFERENCES  D_TYPE_VALUE (CODE) ;


-- 
-- TABLE CONSTRAINT: CONVERSION
-- FOREIGN KEY per la tabella della classe : Conversion class - CONVERSION
-- 

ALTER TABLE CONVERSION ADD CONSTRAINT CONVERSION_FK1 FOREIGN KEY (INPUT) REFERENCES  H_UOM (CODE) ;
ALTER TABLE CONVERSION ADD CONSTRAINT CONVERSION_FK2 FOREIGN KEY (LOCATION) REFERENCES  H_LOCATION (CODE) ;
ALTER TABLE CONVERSION ADD CONSTRAINT CONVERSION_FK3 FOREIGN KEY (OUTPUT) REFERENCES  H_UOM (CODE) ;


-- 
-- Generazione PK e FK per attributi multivalore
-- 


-- 
-- TABLE CONSTRAINT: BUILDINGS_FACADE_MAT
-- FOREIGN KEY per la tabella dell'attributo multivalore : material of facade - FACADE_MAT
-- 

ALTER TABLE BUILDINGS_FACADE_MAT ADD CONSTRAINT BUILDINGS_FACADE_MAT_FK1 FOREIGN KEY (UUID) REFERENCES  BUILDINGS (UUID) ;
ALTER TABLE BUILDINGS_FACADE_MAT ADD CONSTRAINT BUILDINGS_FACADE_MAT_FK2 FOREIGN KEY (FACADE_MAT) REFERENCES  D_MATERIAL (CODE) ;
ALTER TABLE BUILDINGS_FACADE_MAT ADD CONSTRAINT BUILDINGS_FACADE_MAT_PK PRIMARY KEY (UUID ,FACADE_MAT );


-- 
-- TABLE CONSTRAINT: THERMALZONE_HEATINGSOURCE
-- FOREIGN KEY per la tabella dell'attributo multivalore : heatingsource - heatingSource
-- 

ALTER TABLE THERMALZONE_HEATINGSOURCE ADD CONSTRAINT THERMALZONE_HEATINGSOURCE_FK1 FOREIGN KEY (UUID) REFERENCES  THERMALZONE (UUID) ;
ALTER TABLE THERMALZONE_HEATINGSOURCE ADD CONSTRAINT THERMALZONE_HEATINGSOURCE_FK2 FOREIGN KEY (HEATINGSOURCE) REFERENCES  H_ENERGYSOURCE (CODE) ;
ALTER TABLE THERMALZONE_HEATINGSOURCE ADD CONSTRAINT THERMALZONE_HEATINGSOURCE_PK PRIMARY KEY (UUID ,HEATINGSOURCE );


-- 
-- TABLE CONSTRAINT: THERMALZONE_HEATINGSYSTEM
-- FOREIGN KEY per la tabella dell'attributo multivalore : heatingsystem - heatingSystem
-- 

ALTER TABLE THERMALZONE_HEATINGSYSTEM ADD CONSTRAINT THERMALZONE_HEATINGSYSTEM_FK1 FOREIGN KEY (UUID) REFERENCES  THERMALZONE (UUID) ;
ALTER TABLE THERMALZONE_HEATINGSYSTEM ADD CONSTRAINT THERMALZONE_HEATINGSYSTEM_FK2 FOREIGN KEY (HEATINGSYSTEM) REFERENCES  D_HEATINGSYSTEM (CODE) ;
ALTER TABLE THERMALZONE_HEATINGSYSTEM ADD CONSTRAINT THERMALZONE_HEATINGSYSTEM_PK PRIMARY KEY (UUID ,HEATINGSYSTEM );


-- 
-- TABLE CONSTRAINT: BUILDINGS_ROOF_MAT
-- FOREIGN KEY per la tabella dell'attributo multivalore : material of roof - ROOF_MAT
-- 

ALTER TABLE BUILDINGS_ROOF_MAT ADD CONSTRAINT BUILDINGS_ROOF_MAT_FK1 FOREIGN KEY (UUID) REFERENCES  BUILDINGS (UUID) ;
ALTER TABLE BUILDINGS_ROOF_MAT ADD CONSTRAINT BUILDINGS_ROOF_MAT_FK2 FOREIGN KEY (ROOF_MAT) REFERENCES  D_MATERIAL (CODE) ;
ALTER TABLE BUILDINGS_ROOF_MAT ADD CONSTRAINT BUILDINGS_ROOF_MAT_PK PRIMARY KEY (UUID ,ROOF_MAT );


-- 
-- TABLE CONSTRAINT: BUILDINGS_STRUCTURE_MAT
-- FOREIGN KEY per la tabella dell'attributo multivalore : material of structure - STRUCTURE_MAT
-- 

ALTER TABLE BUILDINGS_STRUCTURE_MAT ADD CONSTRAINT BUILDINGS_STRUCTURE_MAT_FK1 FOREIGN KEY (UUID) REFERENCES  BUILDINGS (UUID) ;
ALTER TABLE BUILDINGS_STRUCTURE_MAT ADD CONSTRAINT BUILDINGS_STRUCTURE_MAT_FK2 FOREIGN KEY (STRUCTURE_MAT) REFERENCES  D_MATERIAL (CODE) ;
ALTER TABLE BUILDINGS_STRUCTURE_MAT ADD CONSTRAINT BUILDINGS_STRUCTURE_MAT_PK PRIMARY KEY (UUID ,STRUCTURE_MAT );


-- 
-- Generazione PK e FK per i datatype
-- 


-- 
-- TABLE CONSTRAINT: BUILDINGS_ELEVATION_T
-- PRIMARY KEY e FOREIGN KEY per la tabella delle associzione binaria con attributi: Elevation - ELEVATION
-- 

ALTER TABLE BUILDINGS_ELEVATION_T ADD CONSTRAINT BUILDINGS_ELEVATION_T_FK1 FOREIGN KEY (UUID) REFERENCES  BUILDINGS (UUID) ;
ALTER TABLE BUILDINGS_ELEVATION_T ADD CONSTRAINT BUILDINGS_ELEVATION_T_FK2 FOREIGN KEY (ELEVATION_ELEVATIONREFERENCE) REFERENCES  D_ELEVATIONREFERENCE (CODE) ;
ALTER TABLE BUILDINGS_ELEVATION_T ADD CONSTRAINT BUILDINGS_ELEVATION_T_PK UNIQUE (UUID ,ELEVATION_ELEV_VAL ,ELEVATION_ELEVATIONREFERENCE );


-- 
-- TABLE CONSTRAINT: THERMALZONE_OFFICIALAREA_T
-- PRIMARY KEY e FOREIGN KEY per la tabella delle associzione binaria con attributi: Official area - OFF_AREA
-- 

ALTER TABLE THERMALZONE_OFFICIALAREA_T ADD CONSTRAINT THERMALZONE_OFFICIALAREA_T_FK1 FOREIGN KEY (UUID) REFERENCES  THERMALZONE (UUID) ;
ALTER TABLE THERMALZONE_OFFICIALAREA_T ADD CONSTRAINT THERMALZONE_OFFICIALAREA_T_FK2 FOREIGN KEY (OFFICIALAREA_AREA_REF) REFERENCES  D_CLGE (CODE) ;
ALTER TABLE THERMALZONE_OFFICIALAREA_T ADD CONSTRAINT THERMALZONE_OFFICIALAREA_T_PK PRIMARY KEY (UUID ,OFFICIALAREA_AREA_REF ,OFFICIALAREA_VALUE );


-- 
-- TABLE CONSTRAINT: BUILDINGS_EXT_REF_T
-- PRIMARY KEY e FOREIGN KEY per la tabella delle associzione binaria con attributi: External reference - EXT_REF
-- 

ALTER TABLE BUILDINGS_EXT_REF_T ADD CONSTRAINT BUILDINGS_EXT_REF_T_FK1 FOREIGN KEY (UUID) REFERENCES  BUILDINGS (UUID) ;
ALTER TABLE BUILDINGS_EXT_REF_T ADD CONSTRAINT BUILDINGS_EXT_REF_T_PK PRIMARY KEY (UUID ,EXT_REF_IDENTIFIER ,EXT_REF_INF_SYS_NAME ,EXT_REF_REFERENCE );


-- 
-- TABLE CONSTRAINT: THERMALZONE_ENERGYAMOUNT_T
-- PRIMARY KEY e FOREIGN KEY per la tabella delle associzione binaria con attributi: Energy amount - EnergyAmount
-- 

ALTER TABLE THERMALZONE_ENERGYAMOUNT_T ADD CONSTRAINT THERMALZONE_ENERGYAMOUNT_T_FK1 FOREIGN KEY (UUID) REFERENCES  THERMALZONE (UUID) ;
ALTER TABLE THERMALZONE_ENERGYAMOUNT_T ADD CONSTRAINT THERMALZONE_ENERGYAMOUNT_T_FK2 FOREIGN KEY (ENERGYAMOUNT_E_SOURCE) REFERENCES  H_ENERGYSOURCE (CODE) ;
ALTER TABLE THERMALZONE_ENERGYAMOUNT_T ADD CONSTRAINT THERMALZONE_ENERGYAMOUNT_T_FK3 FOREIGN KEY (ENERGYAMOUNT_E_TYPE) REFERENCES  D_ENERGYTYPE (CODE) ;
ALTER TABLE THERMALZONE_ENERGYAMOUNT_T ADD CONSTRAINT THERMALZONE_ENERGYAMOUNT_T_FK4 FOREIGN KEY (ENERGYAMOUNT_E_USE) REFERENCES  D_ENERGYUSE (CODE) ;
ALTER TABLE THERMALZONE_ENERGYAMOUNT_T ADD CONSTRAINT THERMALZONE_ENERGYAMOUNT_T_FK5 FOREIGN KEY (ENERGYAMOUNT_E_UOM) REFERENCES  H_UOM (CODE) ;
ALTER TABLE THERMALZONE_ENERGYAMOUNT_T ADD CONSTRAINT THERMALZONE_ENERGYAMOUNT_T_PK PRIMARY KEY (UUID ,ENERGYAMOUNT_E_AMOUNT ,ENERGYAMOUNT_E_SOURCE ,ENERGYAMOUNT_E_TYPE ,ENERGYAMOUNT_E_USE ,ENERGYAMOUNT_E_YEAR ,ENERGYAMOUNT_E_UOM ,ENERGYAMOUNT_ESTIMATEDCO2 );


-- 
-- TABLE CONSTRAINT: INSTALLATION_ELEVATION_T
-- PRIMARY KEY e FOREIGN KEY per la tabella delle associzione binaria con attributi: Elevation - ELEVATION
-- 

ALTER TABLE INSTALLATION_ELEVATION_T ADD CONSTRAINT INSTALLATION_ELEVATION_T_FK1 FOREIGN KEY (UUID) REFERENCES  INSTALLATION (UUID) ;
ALTER TABLE INSTALLATION_ELEVATION_T ADD CONSTRAINT INSTALLATION_ELEVATION_T_FK2 FOREIGN KEY (ELEVATION_ELEVATIONREFERENCE) REFERENCES  D_ELEVATIONREFERENCE (CODE) ;
ALTER TABLE INSTALLATION_ELEVATION_T ADD CONSTRAINT INSTALLATION_ELEVATION_T_PK UNIQUE (UUID ,ELEVATION_ELEV_VAL ,ELEVATION_ELEVATIONREFERENCE );


-- 
-- TABLE CONSTRAINT: BUILDINGS_ENERGYAMOUNT_T
-- PRIMARY KEY e FOREIGN KEY per la tabella delle associzione binaria con attributi: Energy amount - EnergyAmount
-- 

ALTER TABLE BUILDINGS_ENERGYAMOUNT_T ADD CONSTRAINT BUILDINGS_ENERGYAMOUNT_T_FK1 FOREIGN KEY (UUID) REFERENCES  BUILDINGS (UUID) ;
ALTER TABLE BUILDINGS_ENERGYAMOUNT_T ADD CONSTRAINT BUILDINGS_ENERGYAMOUNT_T_FK2 FOREIGN KEY (ENERGYAMOUNT_E_SOURCE) REFERENCES  H_ENERGYSOURCE (CODE) ;
ALTER TABLE BUILDINGS_ENERGYAMOUNT_T ADD CONSTRAINT BUILDINGS_ENERGYAMOUNT_T_FK3 FOREIGN KEY (ENERGYAMOUNT_E_TYPE) REFERENCES  D_ENERGYTYPE (CODE) ;
ALTER TABLE BUILDINGS_ENERGYAMOUNT_T ADD CONSTRAINT BUILDINGS_ENERGYAMOUNT_T_FK4 FOREIGN KEY (ENERGYAMOUNT_E_USE) REFERENCES  D_ENERGYUSE (CODE) ;
ALTER TABLE BUILDINGS_ENERGYAMOUNT_T ADD CONSTRAINT BUILDINGS_ENERGYAMOUNT_T_FK5 FOREIGN KEY (ENERGYAMOUNT_E_UOM) REFERENCES  H_UOM (CODE) ;
ALTER TABLE BUILDINGS_ENERGYAMOUNT_T ADD CONSTRAINT BUILDINGS_ENERGYAMOUNT_T_PK PRIMARY KEY (UUID ,ENERGYAMOUNT_E_AMOUNT ,ENERGYAMOUNT_E_SOURCE ,ENERGYAMOUNT_E_TYPE ,ENERGYAMOUNT_E_USE ,ENERGYAMOUNT_E_YEAR ,ENERGYAMOUNT_E_UOM ,ENERGYAMOUNT_ESTIMATEDCO2 );


-- 
-- TABLE CONSTRAINT: BUILDINGS_USE_M_T
-- PRIMARY KEY e FOREIGN KEY per la tabella delle associzione binaria con attributi: Current use - CURR_USE
-- 

ALTER TABLE BUILDINGS_USE_M_T ADD CONSTRAINT BUILDINGS_USE_M_T_FK1 FOREIGN KEY (UUID) REFERENCES  BUILDINGS (UUID) ;
ALTER TABLE BUILDINGS_USE_M_T ADD CONSTRAINT BUILDINGS_USE_M_T_FK2 FOREIGN KEY (USE_M_CURRENTUSE) REFERENCES  H_CURRENTUSE (CODE) ;
ALTER TABLE BUILDINGS_USE_M_T ADD CONSTRAINT BUILDINGS_USE_M_T_PK PRIMARY KEY (UUID ,USE_M_CURRENTUSE ,USE_M_PERCENTAGE );


-- 
-- TABLE CONSTRAINT: BUILDINGS_RENEWABLE_POTENTIA_T
-- PRIMARY KEY e FOREIGN KEY per la tabella delle associzione binaria con attributi: Renewable energy potential - RENEWABLEPOTENTIAL
-- 

ALTER TABLE BUILDINGS_RENEWABLE_POTENTIA_T ADD CONSTRAINT BUILDINGS_RENEWABLE_POTENT_FK1 FOREIGN KEY (UUID) REFERENCES  BUILDINGS (UUID) ;
ALTER TABLE BUILDINGS_RENEWABLE_POTENTIA_T ADD CONSTRAINT BUILDINGS_RENEWABLE_POTENT_FK2 FOREIGN KEY (RENEWABLE_POTEN_RENEWABLE_SOUR) REFERENCES  H_ENERGYSOURCE (CODE) ;
ALTER TABLE BUILDINGS_RENEWABLE_POTENTIA_T ADD CONSTRAINT BUILDINGS_RENEWABLE_POTENTI_PK PRIMARY KEY (UUID ,RENEWABLE_POTEN_RENEWABLE_SOUR ,RENEWABLE_POTENTIAL_VALUE );


-- 
-- TABLE CONSTRAINT: INSTALLATION_EXT_REF_T
-- PRIMARY KEY e FOREIGN KEY per la tabella delle associzione binaria con attributi: External reference - EXT_REF
-- 

ALTER TABLE INSTALLATION_EXT_REF_T ADD CONSTRAINT INSTALLATION_EXT_REF_T_FK1 FOREIGN KEY (UUID) REFERENCES  INSTALLATION (UUID) ;
ALTER TABLE INSTALLATION_EXT_REF_T ADD CONSTRAINT INSTALLATION_EXT_REF_T_PK PRIMARY KEY (UUID ,EXT_REF_IDENTIFIER ,EXT_REF_INF_SYS_NAME ,EXT_REF_REFERENCE );


-- 
-- Generazione degli index per le FK per le classi
-- 


-- 
-- TABLE INDEX: BUILDINGS
-- INDEX per la tabella della classe : Buildings - BUILDINGS
-- 

CREATE INDEX BUILDINGS_IN1 ON BUILDINGS(BUILDINGTYPE);

CREATE INDEX BUILDINGS_IN2 ON BUILDINGS(CONDITION);

CREATE INDEX BUILDINGS_IN3 ON BUILDINGS(ELEV_REF);

CREATE INDEX BUILDINGS_IN4 ON BUILDINGS(HEIGHT_HEIGHT_LOW);

CREATE INDEX BUILDINGS_IN5 ON BUILDINGS(HEIGHT_HEIGHT_REF);

CREATE INDEX BUILDINGS_IN6 ON BUILDINGS(HEIGHT_HEIGHT_STAT);

CREATE INDEX BUILDINGS_IN7 ON BUILDINGS(NATURE);

CREATE INDEX BUILDINGS_IN8 ON BUILDINGS(OWNERSHIP);

CREATE INDEX BUILDINGS_IN9 ON BUILDINGS(REFURBISH);

CREATE INDEX BUILDINGS_IN10 ON BUILDINGS(ROOF_TYPE);

CREATE INDEX BUILDINGS_IN11 ON BUILDINGS(USE_S);



-- 
-- TABLE INDEX: THERMALZONE
-- INDEX per la tabella della classe : Thermal zone (building part) - THERMALZONE
-- 

CREATE INDEX THERMALZONE_IN1 ON THERMALZONE(ENERGYPERFORMANCE_PERF_CLASS);

CREATE INDEX THERMALZONE_IN2 ON THERMALZONE(ENERGYPERFORMANCE_PERF_UOM);

CREATE INDEX THERMALZONE_IN3 ON THERMALZONE(OCCUPANTS_OCC_TYPE);

CREATE INDEX THERMALZONE_IN4 ON THERMALZONE(UUID_TZ2BDG);



-- 
-- TABLE INDEX: INSTALLATION
-- INDEX per la tabella della classe : Installation - INSTALLATION
-- 

CREATE INDEX INSTALLATION_IN1 ON INSTALLATION(CONDITION);

CREATE INDEX INSTALLATION_IN2 ON INSTALLATION(ELEV_REF);

CREATE INDEX INSTALLATION_IN3 ON INSTALLATION(HEIGHT_HEIGHT_LOW);

CREATE INDEX INSTALLATION_IN4 ON INSTALLATION(HEIGHT_HEIGHT_REF);

CREATE INDEX INSTALLATION_IN5 ON INSTALLATION(HEIGHT_HEIGHT_STAT);

CREATE INDEX INSTALLATION_IN6 ON INSTALLATION(INSTALLATION_NATURE);

CREATE INDEX INSTALLATION_IN7 ON INSTALLATION(OWNERSHIP);

CREATE INDEX INSTALLATION_IN8 ON INSTALLATION(TYPE);



-- 
-- TABLE INDEX: CONVERSION
-- INDEX per la tabella della classe : Conversion class - CONVERSION
-- 

CREATE INDEX CONVERSION_IN1 ON CONVERSION(INPUT);

CREATE INDEX CONVERSION_IN2 ON CONVERSION(LOCATION);

CREATE INDEX CONVERSION_IN3 ON CONVERSION(OUTPUT);



-- 
-- Generazione degli index per le FK per attributi multivalore
-- 


-- 
-- TABLE INDEX: BUILDINGS_FACADE_MAT
-- INDEX per la tabella dell'attributo multivalore : material of facade - FACADE_MAT
-- 

CREATE INDEX BUILDINGS_FACADE_MAT_IN1 ON BUILDINGS_FACADE_MAT(UUID);

CREATE INDEX BUILDINGS_FACADE_MAT_IN2 ON BUILDINGS_FACADE_MAT(FACADE_MAT);



-- 
-- TABLE INDEX: THERMALZONE_HEATINGSOURCE
-- INDEX per la tabella dell'attributo multivalore : heatingsource - heatingSource
-- 

CREATE INDEX THERMALZONE_HEATINGSOURCE_IN1 ON THERMALZONE_HEATINGSOURCE(UUID);

CREATE INDEX THERMALZONE_HEATINGSOURCE_IN2 ON THERMALZONE_HEATINGSOURCE(HEATINGSOURCE);



-- 
-- TABLE INDEX: THERMALZONE_HEATINGSYSTEM
-- INDEX per la tabella dell'attributo multivalore : heatingsystem - heatingSystem
-- 

CREATE INDEX THERMALZONE_HEATINGSYSTEM_IN1 ON THERMALZONE_HEATINGSYSTEM(UUID);

CREATE INDEX THERMALZONE_HEATINGSYSTEM_IN2 ON THERMALZONE_HEATINGSYSTEM(HEATINGSYSTEM);



-- 
-- TABLE INDEX: BUILDINGS_ROOF_MAT
-- INDEX per la tabella dell'attributo multivalore : material of roof - ROOF_MAT
-- 

CREATE INDEX BUILDINGS_ROOF_MAT_IN1 ON BUILDINGS_ROOF_MAT(UUID);

CREATE INDEX BUILDINGS_ROOF_MAT_IN2 ON BUILDINGS_ROOF_MAT(ROOF_MAT);



-- 
-- TABLE INDEX: BUILDINGS_STRUCTURE_MAT
-- INDEX per la tabella dell'attributo multivalore : material of structure - STRUCTURE_MAT
-- 

CREATE INDEX BUILDINGS_STRUCTURE_MAT_IN1 ON BUILDINGS_STRUCTURE_MAT(UUID);

CREATE INDEX BUILDINGS_STRUCTURE_MAT_IN2 ON BUILDINGS_STRUCTURE_MAT(STRUCTURE_MAT);



-- 
-- Generazione degli index per le FK per i datatype
-- 


-- 
-- TABLE INDEX: BUILDINGS_ELEVATION_T
-- INDEX per la tabella delle associzione binaria con attributi: Elevation - ELEVATION
-- 

CREATE INDEX BUILDINGS_ELEVATION_T_IN1 ON BUILDINGS_ELEVATION_T(UUID);

CREATE INDEX BUILDINGS_ELEVATION_T_IN2 ON BUILDINGS_ELEVATION_T(ELEVATION_ELEVATIONREFERENCE);



-- 
-- TABLE INDEX: THERMALZONE_OFFICIALAREA_T
-- INDEX per la tabella delle associzione binaria con attributi: Official area - OFF_AREA
-- 

CREATE INDEX THERMALZONE_OFFICIALAREA_T_IN1 ON THERMALZONE_OFFICIALAREA_T(UUID);

CREATE INDEX THERMALZONE_OFFICIALAREA_T_IN2 ON THERMALZONE_OFFICIALAREA_T(OFFICIALAREA_AREA_REF);



-- 
-- TABLE INDEX: BUILDINGS_EXT_REF_T
-- INDEX per la tabella delle associzione binaria con attributi: External reference - EXT_REF
-- 

CREATE INDEX BUILDINGS_EXT_REF_T_IN1 ON BUILDINGS_EXT_REF_T(UUID);



-- 
-- TABLE INDEX: THERMALZONE_ENERGYAMOUNT_T
-- INDEX per la tabella delle associzione binaria con attributi: Energy amount - EnergyAmount
-- 

CREATE INDEX THERMALZONE_ENERGYAMOUNT_T_IN1 ON THERMALZONE_ENERGYAMOUNT_T(UUID);

CREATE INDEX THERMALZONE_ENERGYAMOUNT_T_IN2 ON THERMALZONE_ENERGYAMOUNT_T(ENERGYAMOUNT_E_SOURCE);

CREATE INDEX THERMALZONE_ENERGYAMOUNT_T_IN3 ON THERMALZONE_ENERGYAMOUNT_T(ENERGYAMOUNT_E_TYPE);

CREATE INDEX THERMALZONE_ENERGYAMOUNT_T_IN4 ON THERMALZONE_ENERGYAMOUNT_T(ENERGYAMOUNT_E_USE);

CREATE INDEX THERMALZONE_ENERGYAMOUNT_T_IN5 ON THERMALZONE_ENERGYAMOUNT_T(ENERGYAMOUNT_E_UOM);



-- 
-- TABLE INDEX: INSTALLATION_ELEVATION_T
-- INDEX per la tabella delle associzione binaria con attributi: Elevation - ELEVATION
-- 

CREATE INDEX INSTALLATION_ELEVATION_T_IN1 ON INSTALLATION_ELEVATION_T(UUID);

CREATE INDEX INSTALLATION_ELEVATION_T_IN2 ON INSTALLATION_ELEVATION_T(ELEVATION_ELEVATIONREFERENCE);



-- 
-- TABLE INDEX: BUILDINGS_ENERGYAMOUNT_T
-- INDEX per la tabella delle associzione binaria con attributi: Energy amount - EnergyAmount
-- 

CREATE INDEX BUILDINGS_ENERGYAMOUNT_T_IN1 ON BUILDINGS_ENERGYAMOUNT_T(UUID);

CREATE INDEX BUILDINGS_ENERGYAMOUNT_T_IN2 ON BUILDINGS_ENERGYAMOUNT_T(ENERGYAMOUNT_E_SOURCE);

CREATE INDEX BUILDINGS_ENERGYAMOUNT_T_IN3 ON BUILDINGS_ENERGYAMOUNT_T(ENERGYAMOUNT_E_TYPE);

CREATE INDEX BUILDINGS_ENERGYAMOUNT_T_IN4 ON BUILDINGS_ENERGYAMOUNT_T(ENERGYAMOUNT_E_USE);

CREATE INDEX BUILDINGS_ENERGYAMOUNT_T_IN5 ON BUILDINGS_ENERGYAMOUNT_T(ENERGYAMOUNT_E_UOM);



-- 
-- TABLE INDEX: BUILDINGS_USE_M_T
-- INDEX per la tabella delle associzione binaria con attributi: Current use - CURR_USE
-- 

CREATE INDEX BUILDINGS_USE_M_T_IN1 ON BUILDINGS_USE_M_T(UUID);

CREATE INDEX BUILDINGS_USE_M_T_IN2 ON BUILDINGS_USE_M_T(USE_M_CURRENTUSE);



-- 
-- TABLE INDEX: BUILDINGS_RENEWABLE_POTENTIA_T
-- INDEX per la tabella delle associzione binaria con attributi: Renewable energy potential - RENEWABLEPOTENTIAL
-- 

CREATE INDEX BUILDINGS_RENEWABLE_POTENT_IN1 ON BUILDINGS_RENEWABLE_POTENTIA_T(UUID);

CREATE INDEX BUILDINGS_RENEWABLE_POTENT_IN2 ON BUILDINGS_RENEWABLE_POTENTIA_T(RENEWABLE_POTEN_RENEWABLE_SOUR);



-- 
-- TABLE INDEX: INSTALLATION_EXT_REF_T
-- INDEX per la tabella delle associzione binaria con attributi: External reference - EXT_REF
-- 

CREATE INDEX INSTALLATION_EXT_REF_T_IN1 ON INSTALLATION_EXT_REF_T(UUID);



-- 
-- Generazione degli index spaziali per le classi
-- 


-- 
-- SPATIAL INDEX: BUILDINGS
-- SPATIAL INDEX per la tabella della classe : Buildings - BUILDINGS
-- 

CREATE INDEX BUILDINGS_SI1 ON BUILDINGS(GEOMETRY2D) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('LAYER_GTYPE=MULTIPOLYGON');



-- 
-- SPATIAL INDEX: INSTALLATION
-- SPATIAL INDEX per la tabella della classe : Installation - INSTALLATION
-- 

CREATE INDEX INSTALLATION_SI1 ON INSTALLATION(GEOMETRY2D) INDEXTYPE IS MDSYS.SPATIAL_INDEX PARAMETERS('LAYER_GTYPE=POINT');



-- 
-- Generazione UNIQUE CONSTRAINT per le classi
-- 


-- 
-- Generazione delle insert per la trascodifica dei domini
-- 


-- 
-- INSERT INTO TABLE: D_OCCUPANCYTYPE
-- Valori di trascodifica per il dominio: Occupancy type value - OCCUPANCYTYPE
-- 

INSERT INTO D_OCCUPANCYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('visitors','VISITORS','VISITORS',null);
INSERT INTO D_OCCUPANCYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('workers','WORKERS','WORKERS',null);
INSERT INTO D_OCCUPANCYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('residents','RESIDENTS','RESIDENTS',null);
INSERT INTO D_OCCUPANCYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('patients','PATIENTS','PATIENTS',null);
INSERT INTO D_OCCUPANCYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('other or combination','OTHER','OTHERORCOMBINATION',null);
INSERT INTO D_OCCUPANCYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('students','STUDENTS','STUDENTS',null);


-- 
-- INSERT INTO TABLE: D_BUILDINGNATURE
-- Valori di trascodifica per il dominio: Building nature value - BUILDINGNATURE
-- 

INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('windturbine','windTurbine',null,'A tower and associated equipment that generates electrical power from wind.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('canopy','canopy',null,'An overhead roof providing shelter to things below. 
Canopies may be free standing frameworks over which a covering is attached or may be linked or suspended to the outside of a building');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('mosque','mosque',null,'A building or structure whose primary purpose is to facilitate the muslim cult');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('greenhouse','greenhouse',null,'A building that is often constructed primarily of transparent material (for example: glass), in which temperature and humidity can be controlled for the cultivation and/or protection of plants.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('arch','arch','ARCH','A man-made structure in the form of an arch.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('synagogue','synagogue',null,'A building or structure whose primary purpose is to facilitate the israelit cult.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('windmill','windmill',null,'A building which converts the energy of the wind into rotational motion by means of adjustable sails or blades.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('temple','temple',null,'A building or structure whose primary purpose is to facilitate the meeting of a religious sect.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('chapel','chapel',null,'A Christian place of worship, usually smaller than a church.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('shed','shed',null,'A building of light construction, which usually has one or more open sides, that is typically used for storage.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('tower','tower',null,'A relatively tall, narrow structure that may either stand alone or may form part of another structure.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('lighthouse','lighthouse',null,'A tower designed to emit light from a system of lamps and lenses.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('church','church',null,'Building or structure whose primary aim is to facilitate the religious practice of a Christian community');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('castle','castle',null,'A large ornate or fortified building usually constructed for the purpose of a private residence or security');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('bunker','bunker',null,'A facility, partly underground, intended for or used by the military either for location of command/control centers or for troop encampment.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('silo','silo',null,'A large storage structure, generally cylindrical, used for storing loose materials.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('stadium','stadium',null,'A place or venue for sports, concerts or other events and consists of a field or stage either partly or completely surrounded by a structure designed to allow spectators to stand or sit and view the event.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('storagetank','storageTank',null,'A container usually for holding liquids and compressed gases.');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('dam','dam',null,'A permanent barrier across a watercourse used to impound water or to control its flow');
INSERT INTO D_BUILDINGNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('cavebuilding','caveBuilding',null,'A space hosting human or economic activity which is usually enclosed within rock with the addition of man-made exterior walls and which may contain structures comparable to the interior structures of freestanding buildings');


-- 
-- INSERT INTO TABLE: H_OWNERSHIPTYPE
-- Valori di trascodifica per il dominio gerarchico: Ownership type value - OWNERSHIPTYPE
-- 

INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('non occupant private owner','NONOCCUPANTPRIVATE','NONOCCUPANTPRIVATEOWNER',null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('other or combination','OTHER','OTHER',null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('government','GOVERNMENT','GOVERNMENT',null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('government - european','EUROPEAN',null,null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('government - municipal','MUNICIPAL','MUNICIPAL',null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('government - regional','REGIONAL',null,null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('government - national state','NATIONAL',null,null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('non-profit organisation','NGO','NONPROFITORGANISATION',null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('property management company','PROPERTYCOMPANY','PROPERTYCOMPANY',null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('occupant private owner','OCCUPANTPRIVATE','OCCUPANTPRIVATEOWNER',null);
INSERT INTO H_OWNERSHIPTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('corporation','CORPORATION','CORPORATION',null);


-- 
-- INSERT INTO TABLE: D_BUILDINGTYPE
-- Valori di trascodifica per il dominio: Building type - BUILDINGTYPE
-- 

INSERT INTO D_BUILDINGTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('apartment block','AB','APARTMENTBLOCK',null);
INSERT INTO D_BUILDINGTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('multifamilyhouse','MFH','MULTIFAMILYHOUSE',null);
INSERT INTO D_BUILDINGTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('terraced house','TH','TERRACEDHOUSE',null);
INSERT INTO D_BUILDINGTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('single family house','SFH','SINGLEFAMILYHOUSE',null);


-- 
-- INSERT INTO TABLE: H_LOCATION
-- Valori di trascodifica per il dominio gerarchico: Location - LOCATION
-- 

INSERT INTO H_LOCATION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('europe','EUROPE',null,null);
INSERT INTO H_LOCATION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('europe - portugal','PT',null,null);
INSERT INTO H_LOCATION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('europe - italy','IT',null,null);
INSERT INTO H_LOCATION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('europe - italy - regione emilia-romagna','ITD',null,'ITD is the NUTS code for Regione Emilia-Romagna.');
INSERT INTO H_LOCATION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('europe - greece','GR',null,null);
INSERT INTO H_LOCATION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('world','WORLD',null,'Entire world');


-- 
-- INSERT INTO TABLE: D_ENERGYTYPE
-- Valori di trascodifica per il dominio: Energy type value - ENERGYTYPE
-- 

INSERT INTO D_ENERGYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('demand','demand','DEMAND',null);
INSERT INTO D_ENERGYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('final','final','FINAL',null);
INSERT INTO D_ENERGYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('primary','primary','PRIMARY',null);
INSERT INTO D_ENERGYTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('estimated','estimated','ESTIMATED',null);


-- 
-- INSERT INTO TABLE: D_INSTALLATIONNATURE
-- Valori di trascodifica per il dominio: Installation nature value - INSTALLATIONNATURE
-- 

INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('photovoltaic panel','PHOTOVOLTAICPANEL','PHOTOVOLTAICPANEL',null);
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('cradle','cradle','CRADLE','A small suspended platform that can be moved up and down the outside of a high building, used by people cleaning or maintaining windows or facades, etc.
The cradles that are permanently installed in a building and may be used for emergency evacuation are of interest for INSPIRE.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('antenna','antenna','ANTENNA','A transducer designed to transmit or receive electromagnetic waves (includes radio and television masts, radar towers and satellite telecommunications).
Only antennas attached to buildings shall be considered as Installation. Self-standing antennas shall be considered as OtherConstruction');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('tower','tower','TOWER','A relatively tall, narrow structure that may either stand alone or may form part of another structure.
May be considered as installations only the small towers that form part of a building, especially if they are not attached to the ground. More significant and/or more independent towers shall be considered as Building or BuildingPart.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('arcade','arcade','ARCADE','An arcade is a covered passage, usually with shops on one or both sides.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('stairway','stairway','STAIRWAY','Stairway is a construction designed to bridge a large vertical distance by dividing it into smaller vertical distances, called steps. Stairways may be straight, round, or may consist of two or more straight pieces connected at angles.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('air duct','airDuct','AIRDUCT','Ducts for incoming (fresh) and outgoing (stale) air.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('externallift','externalLift','EXTERNALLIFT','Lift moving along the outside of a building.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('balcony','balcony','BALCONY','A balcony is a upper accessible platform within a storey, not fully enclosed by wall(s).');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('solarpanel','solarPanel','SOLARPANEL','A solar panel is a packaged, connected assembly of solar cells, also known as photovoltaic cells. The solar panel can be used as a component of a larger photovoltaic system to generate and supply electricity in commercial and residential applications.
Only the solar panels attached to the building should be considered as installations. The self-standing solar panels should be classified under OtherConstruction.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('railing','railing','RAILING','A handrail is a rail that is designed to be grasped by the hand so as to provide stability or support.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('air conditioning unit','airConditioningUnit','AIRCONDITIONINGUNIT','An air conditioning unit or air conditioner is a home appliance, system, or mechanism designed to dehumidify and extract heat from an area.
Only the external air conditioning units located outside the building shall be considered as Installation.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('chimney','chimney','CHIMNEY','A vertical structure containing a passage or flue for discharging smoke and gases of combustion.
Only chimneys attached to buildings shall be considered as Installation. Self-standing chimneys shall be considered as OtherConstruction.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('dormer','dormer','DORMER','A dormer is a structural element of a building that protrudes from the plane of a sloping roof surface. Dormers are used, either in original construction or as later additions, to create usable space in the roof of a building by adding headroom and usually also by enabling addition of windows.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('ramp','ramp','RAMP','A ramp is an inclined plane installed in addition to or instead of stairs. A ramp may generally be used by wheelchairs.');
INSERT INTO D_INSTALLATIONNATURE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('windturbine','windTurbine','WINDTURBINE','A device that converts kinetic energy from the wind into mechanical energy.
Only the (generally small) wind turbines attached to or serving a building shall be classified under installations. The self-standing and generally big wind-turbines shall be classified under Building.');


-- 
-- INSERT INTO TABLE: H_ENERGYSOURCE
-- Valori di trascodifica per il dominio gerarchico: Energy source value - ENERGYSOURCE
-- 

INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('liquidfuels','liquidFuels','LIQUIDFUELS','Liquid fuels include all sorts of liquids, petroleum, fuel oil etc.');
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('warmwaterorstream','warmwarmWaterOrStream','WARMWATERORSTREAM','Warm water or stream is generally distributed by central district heating.');
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('naturalgas','naturalGas','NATURALGAS','The source is fossil gas distributed by pipeline.');
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('straw','straw','STRAW','The source is solid biofuels from straw and agricultural waste.');
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('renewable','renewable','RENEWABLE',null);
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('renewable - solar','solar','SOLAR',null);
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('renewable - hydro','hydro','HYDRO',null);
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('renewable - wind','wind','WIND',null);
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('renewable - geothermal','geothermal','GEOTHERMAL',null);
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('renewable - biomass','biomass','BIOMASS',null);
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('renewable - biofuel','biofuel','BIOFUEL',null);
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('solidfuels','solidFuels','SOLIDFUELS','Solid fuels include wood, charcoal, peat, coal, tablets and pellets made from wood.');
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('electricity','electricity','ELECTRICITY','The source is electricity distributed from power plant.');
INSERT INTO H_ENERGYSOURCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('biogas','biogas','BIOGAS','Biogas may come from a local biogas plant or more rarely be produced on a household scale.');


-- 
-- INSERT INTO TABLE: D_PERF_CLASS
-- Valori di trascodifica per il dominio: Energy performance class - PERF_CLASS
-- 

INSERT INTO D_PERF_CLASS (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('c','C','C','Third class according to the energy performance of the building.');
INSERT INTO D_PERF_CLASS (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('a','A','A','First class according to the energy performance of the building (i.e. the most efficient buildings for energy performance).');
INSERT INTO D_PERF_CLASS (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('b','B','B','Second class according to the energy performance of the building.');
INSERT INTO D_PERF_CLASS (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('d','D','D','Fourth class according to the energy performance of the building.');
INSERT INTO D_PERF_CLASS (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('f','F','F','Sixth class according to the energy performance of the building.');
INSERT INTO D_PERF_CLASS (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('e','E','E','Fifth class according to the energy performance of the building.');
INSERT INTO D_PERF_CLASS (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('g','G','G','Seventh and last class according to the energy performance of the building (i.e. the least efficient buildings for energy performance).');


-- 
-- INSERT INTO TABLE: D_CLGE
-- Valori di trascodifica per il dominio: Clge official area reference value - CLGE
-- 

INSERT INTO D_CLGE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('internalprimaryarea','internalPrimaryArea','INTERNALPRIMARYAREA','Internal primary area is the sum of all floor areas with a heightroom superior or equal to heightParameter and that are associated with the principal uses of the building.
Internal primary area includes: 
- in housing: living areas (dining rooms, bedrooms), toilet, areas (bathrooms, lavatories), interior space and passageways, storage areas... 
- in offices: work areas, meeting rooms, annexes, recreational areas, toilets, interior space and passageways...');
INSERT INTO D_CLGE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('internalresidualarea','internalResidualArea','INTERNALRESIDUALAREA','Internal residual area is the sum of all floor areas regardless of height that are not consistent with the principal use of the building.
Internal residual area includes in particular underground storage and archive rooms, cellars, parking garage, balconies, upper floor terraces, loggias.');
INSERT INTO D_CLGE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('internalotherarea','internalOtherArea','INTERNALOTHERAREA','Internal other area is the sum of all floor areas with a heightroom < heightParameter and that are associated with the main uses of the building.
Internal other areas includes in particular garages, passageways and non-enclosed covered area (canopies, car-ports, ...).');
INSERT INTO D_CLGE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('constructedarea','constructedArea','CONSTRUCTEDAREA','Constructed area is the difference between the external area and the internal area of the building or building unit.
NOTE: Constructed area is mainly used as technical data.');
INSERT INTO D_CLGE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('externalarea','externalArea','EXTERNALAREA','External area is the area within the outer perimeter boundary of a building or building unit, including any outer cladding, measured at floor level.
NOTE: External area is mainly used for spatial planning purpose.');
INSERT INTO D_CLGE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('internalservicearea','internalServiceArea','INTERNALSERVICEAREA','Internal service area is the sum of all floor areas used for building services, irrespective of their height or occupation.
Internal service area includes in particular lift shafts, stairwells, access ramps, maintenance and technical areas serving the building.');
INSERT INTO D_CLGE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('internalarea','internalArea','INTERNALAREA','Internal area is the area within the interior perimeter of a building or building unit, measured above skirting-board level.
Internal area is mainly used as reference unit of measure in valuation, property transaction, renting and building management.');


-- 
-- INSERT INTO TABLE: D_TYPE_VALUE
-- Valori di trascodifica per il dominio: Type value - TYPE_VALUE
-- 

INSERT INTO D_TYPE_VALUE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('other','OTHER','OTHER',null);
INSERT INTO D_TYPE_VALUE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('bipv','BIPV','BIPV',null);
INSERT INTO D_TYPE_VALUE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('on building','ONBUILDING','ONBUILDING',null);
INSERT INTO D_TYPE_VALUE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('not integrated','NOTINTEGRATED','NOTINTEGRATED',null);
INSERT INTO D_TYPE_VALUE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('on other construction','ONOTHERCONSTRUCTION','ONOTHERCONSTRUCTION',null);
INSERT INTO D_TYPE_VALUE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('partially integrated','PARTIALLYINTEGRATED','PARTIALLYINTEGRATED',null);
INSERT INTO D_TYPE_VALUE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('integrated','INTEGRATED','INTEGRATED',null);


-- 
-- INSERT INTO TABLE: D_HEIGHTSTATUS
-- Valori di trascodifica per il dominio: Height status value - HEIGHTSTATUS
-- 

INSERT INTO D_HEIGHTSTATUS (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('estimated','estimated',null,'The height has been estimated and not measured.');
INSERT INTO D_HEIGHTSTATUS (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('measured','measured',null,'The height has been (directly or indirectly) measured');


-- 
-- INSERT INTO TABLE: H_CURRENTUSE
-- Valori di trascodifica per il dominio gerarchico: Current use value - CURRENTUSE
-- 

INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('ancillary','ancillary',null,'A building (or building component) of small size that is used only in connection with another larger building (or building component) and generally does not inherit the same function and characteristics as the building (or building component) it is 
linked to.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('residential','residential',null,'The building (or building component) is used for residential purpose.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('residential - individualresidence','individualResidence',null,'The building (or building component) hosts only one dwelling.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('residential - collectiveresidence','collectiveResidence',null,'The building (or building component) hosts more than one dwelling.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('residential - collectiveresidence - twodwellings','twoDwellings',null,'The building (or building component) hosts two dwellings.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('residential - collectiveresidence - morethantwodwelling','moreThanTwoDwelling',null,'The building (or building component) hosts at least 3 dwellings.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('residential - residenceforcommunities','residenceForCommunities',null,'The building (or building component) hosts a residence for communities.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('industrial','industrial',null,'The building (or building component) is used for secondary sector activities (industrial).');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('commerceandservices','commerceAndServices',null,'The building (or building component) is used for any service activities. 
This value addresses the buildings and building components dedicated to tertiary sector activities (commercial and services).');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('commerceandservices - office','office',null,'The building (or building component) hosts offices.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('commerceandservices - trade','trade',null,'The building (or building component) hosts trade activities.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('commerceandservices - publicservices','publicServices',null,'The building (or building component) hosts public services. Public services are tertiary services provided for the benefit of the citizens.');
INSERT INTO H_CURRENTUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('agriculture','agriculture',null,'The building (or building component) is used for agricultural activities.');


-- 
-- INSERT INTO TABLE: D_CONDITIONOFCONSTRUCTION
-- Valori di trascodifica per il dominio: Condition of construction value - CONDITIONOFCONSTRUCTION
-- 

INSERT INTO D_CONDITIONOFCONSTRUCTION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('functional','functional','FUNCTIONAL','The construction is functional.
NOTE: The construction may be used under normal conditions for its current use value(s).');
INSERT INTO D_CONDITIONOFCONSTRUCTION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('declined','declined','DECLINED','The construction cannot be used under normal conditions, though its main elements (walls, roof) are still present.
EXAMPLE: A house whose windows have been for a long time broken or walled up (even if occupied by squatters).');
INSERT INTO D_CONDITIONOFCONSTRUCTION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('demolished','demolished','DEMOLISHED','The construction has been demolished. There are no more visible remains.');
INSERT INTO D_CONDITIONOFCONSTRUCTION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('under construction','under construction','UNDER CONSTRUCTION','The construction is under construction and not yet functional. This applies only to the initial construction of the construction and not to maintenance work.');
INSERT INTO D_CONDITIONOFCONSTRUCTION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('projected','projected','PROJECTED','The construction is being designed. Construction has not yet started.');
INSERT INTO D_CONDITIONOFCONSTRUCTION (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('ruin','ruin','RUIN','The construction has been partly demolished and some main elements (roof, walls) have been destroyed. There are some visible remains of the construction.');


-- 
-- INSERT INTO TABLE: D_ENERGYUSE
-- Valori di trascodifica per il dominio: Energy use value - ENERGYUSE
-- 

INSERT INTO D_ENERGYUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('cooling','cooling','COOLING',null);
INSERT INTO D_ENERGYUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('electrical appliances','electricalAppliances','ELECTRICALAPPLIANCES',null);
INSERT INTO D_ENERGYUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('electrical equipments','electricalEquipments','ELECTRICALEQUIPMENTS',null);
INSERT INTO D_ENERGYUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('domestic hot water','domesticHotWater','DOMESTICHOTWATER',null);
INSERT INTO D_ENERGYUSE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('heating','heating','HEATING',null);


-- 
-- INSERT INTO TABLE: D_REFURBISHMENTLEVEL
-- Valori di trascodifica per il dominio: Refurbishment level - REFURBISHMENTLEVEL
-- 

INSERT INTO D_REFURBISHMENTLEVEL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('no refurbishment','norefurbishment','NOREFURBISHMENT','No refurbishment occurred for the building.');
INSERT INTO D_REFURBISHMENTLEVEL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('advanced','advanced','ADVANCED','High refurbishment occurred for the building.');
INSERT INTO D_REFURBISHMENTLEVEL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('standard','standard','STANDARD','Basic refurbishment occurred for the building.');


-- 
-- INSERT INTO TABLE: D_ROOFTYPE
-- Valori di trascodifica per il dominio: Roof type value - ROOFTYPE
-- 

INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('hyperbolicparabaloidalroof','hyperbolicParabaloidalRoof','HYPERBOLICPARABALOIDALROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('pavilionroof','pavilionRoof','PAVILIONROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('domedroof','domedRoof','DOMEDROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('archroof','archRoof','ARCHROOF','archRoof');
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('mansardroof','mansardRoof','MANSARDROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('hippedroof','hippedRoof','HIPPEDROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('monopitchroof','monopitchRoof','MONOPITCHROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('dualpentroof','dualPentRoof','DUALPENTROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('flatroof','flatRoof','FLATROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('halfhippedroof','halfHippedRoof','HALFHIPPEDROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('gabledroof','gabledRoof','GABLEDROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('sawtoothroof','sawToothRoof','SAWTOOTHROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('pyramidalbroachroof','pyramidalBroachRoof','PYRAMIDALBROACHROOF',null);
INSERT INTO D_ROOFTYPE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('conicalroof','conicalRoof','CONICALROOF',null);


-- 
-- INSERT INTO TABLE: D_ELEVATIONREFERENCE
-- Valori di trascodifica per il dominio: Elevation reference - ELEVATIONREFERENCE
-- 

INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('topofconstruction','topOfConstruction',null,'The elevation has been captured at the top level of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('highestpoint','highestPoint',null,'The elevation has been captured at the highest point of the construction, including the installations, such as chimneys and antennas.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('generaleave','generalEave',null,'The elevation has been captured at eave level, anywhere between the lowest and the highest eave levels of the construction');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('highestgroundpoint','highestGroundPoint',null,'The elevation has been captured at the highest ground point of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('generalground','generalGround',null,'The elevation has been captured at ground level, anywhere between the lowest and the highest ground points of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('lowesteave','lowestEave',null,'The elevation has been captured at the lowest eave level of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('highesteave','highestEave',null,'The elevation has been captured at the highest eave level of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('generalroof','generalRoof',null,'The elevation has been captured at roof level, anywhere between the lowest edge roof level and the top of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('abovegroundenvelope','aboveGroundEnvelope',null,'The elevation has been captured at the level of the maximum extent of the above ground envelope of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('lowestgroundpoint','lowestGroundPoint',null,'The elevation has been captured at the lowest ground point level of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('lowestflooraboveground','lowestFloorAboveGround',null,'The elevation has been captured at the level of the lowest floor above ground.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('highestroofedge','highestRoofEdge',null,'The elevation has been captured at the highest roof edge level of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('entrancepoint','entrancePoint',null,'The elevation has been captured at the entrance of the construction, generally the bottom of entrance door.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('lowestroofedge','lowestRoofEdge',null,'The elevation has been captured at the lowest roof edge level of the construction');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('bottomofconstruction','bottomOfConstruction',null,'The elevation has been captured at the bottom of the usable part of the construction.');
INSERT INTO D_ELEVATIONREFERENCE (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('generalroofedge','generalRoofEdge',null,'The elevation has been captured at roof edge level, anywhere between the lowest and the highest roof edges of the construction.');


-- 
-- INSERT INTO TABLE: D_MATERIAL
-- Valori di trascodifica per il dominio: Material value - MATERIAL
-- 

INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('rublestonemasonry','rubleStoneMasonry','RUBLESTONEMASONRY','Ruble stone is field stone. Is a masonry technique that incorporates any material found or recovered, such as dressed blocks, broken fragments, brick or flint.
NOTE 1: The success of rubble depends on the thickness of the wall and the strength of the binding mortar. If either is too thin, the structure will fail. As it is almost impossible to construct a thin rubble wall, owing to the irregularity of the material and the size of the gaps to be filled by the mortar, in areas or building traditions lacking dressed stone and ashlar technology, rubble walls are likely to be very thick.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('woodshinglesorshakes','woodShinglesOrShakes','WOODSHINGLESORSHAKES','Wood shingles or shakes are differentiated by size and texture. Shingles are cut to a specific size and have smooth finish. Shakes are rough-textures and are irregular in shape.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('mudwalls','mudWalls','MUDWALLS','Mud walls may be made of stacked earth or poured earth. Stacked earth consists in forming balls of plastic soil, which are freshly stacked on each other. Poured earth walls on the other hand are erected between formwork using a sandy material with coarse to fine granular particles. The ultimate finish can be natural - from the formwork- or sand blasted.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('earth','earth','EARTH','Rammed earth or pneumatically impacted stabilized earth. Rammed earth construction (also referred to as tapial in Spanish, or else, pis? de terre, in France) is conducted by erecting wooden or metal forms for the walls and filling them with a moist cement stabilized earth mix which is compacted by pounding with hand tools (with conical or flat heads) or with a mechanical compactor. Metal rebar is often added to further increase ductility.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('precastconcrete','precastConcrete','PRECASTCONCRETE','Precast wall panel construction. Buildings of this type are low-rise structures with precast reinforced concrete wall panels that are often poured on the ground and tilted into place. Roofs are often composed of either plywood sheathing or metal decking, and glass curtain walls may exist at the building perimeter.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('reinforcedmasonry','reinforcedMasonry','REINFORCEDMASONRY','Buildings of this type have exterior walls consisting of grouted (with concrete) masonry (clay brick or concrete block masonry) with internal reinforcing steel rods.
Reinforced masonry buildings are relatively thick walled box-like structures and often have small windows and at least two mostly solid walls.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('naturalstone','naturalStone','NATURALSTONE','The facade is covered with natural stone, such as granite or marble, and may come in different colours and finishing.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('asbestos','asbestos','ASBESTOS','Facade constructed out of asbestos.
Set of six naturally occurring silicate minerals, which all have in common their eponymous asbestiform habit: long (roughly 1:20 aspect ratio), thin fibrous crystals, with each visible fiber composed of millions of microscopic "fibrils" that can be released by abrasion and other processes');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('ceramictiles','ceramicTiles','CERAMICTILES','Ceramic tiles of different colours and design are used for covering the facade of the building');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('firedbrickmasonry','firedBrickMasonry','FIREDBRICKMASONRY','Parts of slums/squatters. Informal constructions are non-engineered and are built by self-builders without any professional input (i.e. neither during the design phase, nor the construction one).');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('slate','slate','SLATE','Slate is a shingle-like sliver of rock or natural stone, offering a natural look laid out in a variety of patterns. It comes in different sizes and colours, although colours are limited to those found in nature.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('mobilehomes','mobileHomes','MOBILEHOMES','A structure designed or adapted for human habitation which is capable of being moved from one place to another (whether by being towed, or by being transported on a motor vehicle or trailer) and any motor vehicle so designed or adapted.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('limestone','limestone','LIMESTONE','The facade of the building is composed of limestone, a sedimentary rock composed largely of calcite and/or aragonite.
Limestone was commonly used for the construction of many medieval churches and castles in Europe, it was widely used in the 19th and early 20th centuries, and in countries like Malta, for a long time, the only building material available.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('steel','steel','STEEL','The load resisting system of the building is made of structural steel, which may be made composite with reinforced concrete at floor slabs. Steel structures may be constructed as moments resisting frames, as concentrically or eccentrically braced frames, or as spatial trusses. The members of the structure may be bolted or welded.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('hotmoppedasphalt','hotMoppedAsphalt','HOTMOPPEDASPHALT','Hot mopped asphalt roofing is usually applied to flat or semi-flat residential roofs that have good access and proper drainage.
NOTE: In residential use it is often covered with a layer of decorative stone to improve the appearance.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('wood','wood','WOOD','The facade of the building is covered with wood, timber or lumber');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('composite','composite','COMPOSITE','Composite material, such as plastics, PVC and fibreglass are used to cover the facade of the building');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('composition','composition','COMPOSITION','Composition shingles are the most widely used roofing material. They are also called asphalt shingles that could either be organic fibre mat or fibreglass core. Both types are steeped in asphalt and then coated with mineral granules to add colour and texture. Most shingles have an adhesive back that when reinforced with tacks, staples or nails for attaching on roof frames would result in a tight fit.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('vegetatedgreenroof','vegetatedGreenRoof','VEGETATEDGREENROOF','Also known as eco-roofs, a vegetated or green roof is a roof of a building that is partially or completely covered with vegetation and a growing medium, planted over a waterproofing membrane. It may also include additional layers such as a root barrier and drainage and irrigation systems.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('glass','glass','GLASS','The surface is constructed out of glass, typically used in roofs covering internal atriums or in greenhouses.
In case of facade, structural glass is used for glazing the facade of buildings through the use of curtain wall systems, frameless glazing systems, polycarbonate sheeting or architectural flat glass.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('corrugatedsheet','corrugatedSheet','CORRUGATEDSHEET','Roofs of corrugated sheet may be of fibreglass, PVC or metal; less frequent is the use of galvanized iron sheet.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('massivestonemasonry','massiveStoneMasonry','MASSIVESTONEMASONRY','Massive stone masonry with lime/cement mortar. Is constructed with a coursed double leaf masonry, with the outer layers of stonework levelled as the construction progresses and follows a well established masonry bond. The stone units are cut in regular dimensions. To improve the connection between cross walls better quality units are used for the bond in these areas.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('vegetated','vegetated','VEGETATED','The facade is covered with vegetation and a growing medium, planted over a waterproofing membrane');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('thatch','thatch','THATCH','Roofs are built by thatching, which is the craft of building a roof with dry vegetation such as straw, water reed, sedge, rushes and heather, layering the vegetation so as to shed water away from the inner roof.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('masonry','masonry','MASONRY','The facade consists of individual units made of fired clay brick or concrete block laid in and bound together by mortar.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('metal','metal','METAL','The surface of the building is covered with metal in the form of galvanized steel with paint, aluminium with paint, stainless steel, zinc, lead or copper.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('concretetile','concreteTile','CONCRETETILE','Roofing material consisting of shingles, simulated wood shakes, lighter-weight tiles and concrete panels manufactured from a variety of fibre-reinforced cement products.
NOTE 1: Some are coated with plastics, enamels, or thin metals, and some contain recycled material. 
NOTE 2: Many concrete tiles mimic the appearance of wood shakes, while improving on the durability and fire protection that real wood affords. It can approximate the look of clay tile or slate while mitigating the structural problems caused by the weight of the real material.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('adobeblockwalls','adobeBlockWalls','ADOBEBLOCKWALLS','Also known as moulded earth, is a building technique that involves the use of clay bricks (adobe) formed in moulds and (traditionally) dried in the sun.
NOTE: These unbaked bricks consist of sand, sometimes gravel, clay, water and often straw or grass mixed together by hand, formed in wooden moulds and dried by the sun. When machinery is not available, earth is manually tamped in the mould; else, mechanical compression is used (manual, or motorized presses), in order to accommodate large production outputs of compressed earth blocks.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('concrete','concrete','CONCRETE','The surface of the facade is constructed out of (reinforced, with bars or fibres-other than asbestos) concrete');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('adobe','adobe','ADOBE','Use of a particular type of masonry for the fa?ade, that involves the use of clay bricks (adobe) formed in moulds and (traditionally) dried in the sun.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('stonemasonryblock','stoneMasonryBlock','STONEMASONRYBLOCK','The load resisting system of the building is made of wood, timber or lumber.
Two systems of construction are possible, one based on a frame, the other on a skeleton. Framing is a building technique based around structural members, usually called studs, which provide a stable frame to which interior and exterior wall coverings are attached. In skeleton houses the posts and the horizontal crossbars form a frame (whose strength is sometimes increased by the use of additional diagonal bracings or stiffeners) that is filled in with wood (post or frame and plank constructions) or other materials such as clay, stone, or brick. This category is also known as timber framing or half-timbered.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('reinforcedconcrete','reinforcedConcrete','REINFORCEDCONCRETE','Roofs constructed out of reinforced concrete, normally along flat or semi-flat surfaces used in terraces or inclined roofs.
For facades and structures, the load resisting system is made of reinforced concrete, a combination of steel reinforcement bars embedded in concrete that act together in resisting forces. Reinforced concrete buildings may be constructed as moment resisting frames (beams and columns framing at nodes), or in combination with shear walls.');
INSERT INTO D_MATERIAL (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('concreteblockmasonry','concreteBlockMasonry','CONCRETEBLOCKMASONRY','Unreinforced concrete block masonry, with lime/cement mortar.
Buildings of this type have perimeter walls, and possibly some interior walls, constructed of unreinforced concrete blocks joined with lime/cement mortar. These perimeter walls are sometimes used as load bearing walls and have no internal reinforcing steel rods. Anchor plates are sometimes used to tie the walls to the floors and roof and are conspicuous from the outside of the structure.');


-- 
-- INSERT INTO TABLE: D_HEATINGSYSTEM
-- Valori di trascodifica per il dominio: Heating system value - HEATINGSYSTEM
-- 

INSERT INTO D_HEATINGSYSTEM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('portablegasheating','portableGasHeating','PORTABLEGASHEATING','Heating is performed by a portable device using liquefied petroleum gas.');
INSERT INTO D_HEATINGSYSTEM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('solarheating','solarHeating','SOLARHEATING','The heating is performed by a solar collector heating the air or liquid based heating system.
This value is usually not used for solar cells producing electricity.');
INSERT INTO D_HEATINGSYSTEM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('districtheating','districtHeating','DISTRICTHEATING','The public heat network is connected to the central heating of the building by a heat exchanger. The warm water or steam used in the district heating system is not mixed with the water of the central heating system in the building.');
INSERT INTO D_HEATINGSYSTEM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('centralheating','centralHeating','CENTRALHEATING','Central heating system performed at building or at building unit level.');
INSERT INTO D_HEATINGSYSTEM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('electricraditors','electricRaditors','ELECTRICRADITORS','Electric radiators could be single portable units or an integrated installation of the building.');
INSERT INTO D_HEATINGSYSTEM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('heatpump','heatPump','HEATPUMP','The heating is performed by a heat pump that transfers thermal energy from an air source or geothermal source.
The device is sometimes connected to the central heating system in the building.');
INSERT INTO D_HEATINGSYSTEM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('stove','stove','STOVE','Stove includes all kinds of devices designed to burn solid fuel, traditionally wood etc. including masonry fireplaces, tile stoves and fire stoves made of cast iron.');


-- 
-- INSERT INTO TABLE: H_UOM
-- Valori di trascodifica per il dominio gerarchico: Unit of measure - UOM
-- 

INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('volume','VOLUME',null,'Unit of measure for volumes.');
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('volume - cube meter','M3',null,null);
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('area','AREA',null,'Unit of measures for areas');
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('area - square feet','F2',null,null);
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('area - square meter','M2',null,null);
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('energy performance','E_Performance','ENERGYPERFORMANCE',null);
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('energy performance - kwh/m2/a (kwh per square meter / annum)','KWH-M2-A',null,'Kilowatt per hour for single square meter, at annual base');
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('energy performance - kwh/m3/a (kwh per cube meter / annum)','KWH-M3-A',null,'Kilowatt per hour for single cube meter, at annual base');
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('energy amount','E_Amount','ENERGYAMOUNT',null);
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('energy amount - watt hour','WH','WATTHOUR',null);
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('energy amount - kilowatt hour','KWH','KILOWATTHOUR',null);
INSERT INTO H_UOM (NAME,CODE,ALPHACODE,DEFINITION) VALUES ('energy amount - megawatt hour','MWH','MEGAWATTHOUR',null);



-- 
-- Generazione completata in 0.277 secondi
-- 

